export type DestinationOption = {
  id: string
  city: string
  country: string
  countryCode: string
  label: string
  aliases: string[]
  coverImageUrl?: string
  timezone?: string
  currency?: string
  language?: string
}

export type ResolvedDestinationInput = {
  id: string | null
  label: string
  city: string | null
  country: string | null
  countryCode: string | null
  coverImageUrl: string | null
  timezone: string | null
  currency: string | null
  language: string | null
  matchedCatalog: boolean
}

export const DESTINATION_CATALOG: DestinationOption[] = [
  {
    id: "rio-de-janeiro-br",
    city: "Rio de Janeiro",
    country: "Brasil",
    countryCode: "BR",
    label: "Rio de Janeiro, Brasil",
    aliases: ["rio", "rio de", "rj"],
    coverImageUrl: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1920&q=80",
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "sao-paulo-br",
    city: "Sao Paulo",
    country: "Brasil",
    countryCode: "BR",
    label: "Sao Paulo, Brasil",
    aliases: ["sao paulo", "sp"],
    coverImageUrl: "https://images.unsplash.com/photo-1543059080-f9b1272213d5?w=1920&q=80",
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "gramado-br",
    city: "Gramado",
    country: "Brasil",
    countryCode: "BR",
    label: "Gramado, Brasil",
    aliases: ["gramado serra gaucha"],
    coverImageUrl: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1920&q=80",
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "florianopolis-br",
    city: "Florianopolis",
    country: "Brasil",
    countryCode: "BR",
    label: "Florianopolis, Brasil",
    aliases: ["floripa", "florianopolis", "florianopolis sc"],
    coverImageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920&q=80",
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "salvador-br",
    city: "Salvador",
    country: "Brasil",
    countryCode: "BR",
    label: "Salvador, Brasil",
    aliases: ["salvador bahia", "ssa"],
    coverImageUrl: "https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=1920&q=80",
    timezone: "America/Bahia",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "foz-do-iguacu-br",
    city: "Foz do Iguacu",
    country: "Brasil",
    countryCode: "BR",
    label: "Foz do Iguacu, Brasil",
    aliases: ["foz", "iguacu", "cataratas"],
    coverImageUrl: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1920&q=80",
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "buenos-aires-ar",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    label: "Buenos Aires, Argentina",
    aliases: ["buenos aires"],
    coverImageUrl: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=1920&q=80",
    timezone: "America/Argentina/Buenos_Aires",
    currency: "ARS",
    language: "es-AR",
  },
  {
    id: "santiago-cl",
    city: "Santiago",
    country: "Chile",
    countryCode: "CL",
    label: "Santiago, Chile",
    aliases: ["santiago do chile", "scl"],
    coverImageUrl: "https://images.unsplash.com/photo-1544989164-22ad3f104515?w=1920&q=80",
    timezone: "America/Santiago",
    currency: "CLP",
    language: "es-CL",
  },
  {
    id: "paris-fr",
    city: "Paris",
    country: "Franca",
    countryCode: "FR",
    label: "Paris, Franca",
    aliases: ["paris france"],
    coverImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1920&q=80",
    timezone: "Europe/Paris",
    currency: "EUR",
    language: "fr-FR",
  },
  {
    id: "londres-gb",
    city: "Londres",
    country: "Reino Unido",
    countryCode: "GB",
    label: "Londres, Reino Unido",
    aliases: ["london", "londres uk"],
    coverImageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1920&q=80",
    timezone: "Europe/London",
    currency: "GBP",
    language: "en-GB",
  },
  {
    id: "lisboa-pt",
    city: "Lisboa",
    country: "Portugal",
    countryCode: "PT",
    label: "Lisboa, Portugal",
    aliases: ["lisbon", "lisboa pt"],
    coverImageUrl: "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=1920&q=80",
    timezone: "Europe/Lisbon",
    currency: "EUR",
    language: "pt-PT",
  },
  {
    id: "roma-it",
    city: "Roma",
    country: "Italia",
    countryCode: "IT",
    label: "Roma, Italia",
    aliases: ["rome", "roma italia"],
    coverImageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1920&q=80",
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  },
  {
    id: "madrid-es",
    city: "Madrid",
    country: "Espanha",
    countryCode: "ES",
    label: "Madrid, Espanha",
    aliases: ["madrid espana"],
    coverImageUrl: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1920&q=80",
    timezone: "Europe/Madrid",
    currency: "EUR",
    language: "es-ES",
  },
  {
    id: "nova-york-us",
    city: "Nova York",
    country: "Estados Unidos",
    countryCode: "US",
    label: "Nova York, Estados Unidos",
    aliases: ["new york", "nyc", "nova iorque"],
    coverImageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1920&q=80",
    timezone: "America/New_York",
    currency: "USD",
    language: "en-US",
  },
  {
    id: "orlando-us",
    city: "Orlando",
    country: "Estados Unidos",
    countryCode: "US",
    label: "Orlando, Estados Unidos",
    aliases: ["orlando florida"],
    coverImageUrl: "https://images.unsplash.com/photo-1515260268569-9271009adfdb?w=1920&q=80",
    timezone: "America/New_York",
    currency: "USD",
    language: "en-US",
  },
  {
    id: "miami-us",
    city: "Miami",
    country: "Estados Unidos",
    countryCode: "US",
    label: "Miami, Estados Unidos",
    aliases: ["miami florida"],
    coverImageUrl: "https://images.unsplash.com/photo-1514214246283-d427a95c5d2f?w=1920&q=80",
    timezone: "America/New_York",
    currency: "USD",
    language: "en-US",
  },
  {
    id: "cancun-mx",
    city: "Cancun",
    country: "Mexico",
    countryCode: "MX",
    label: "Cancun, Mexico",
    aliases: ["cancun mexico"],
    coverImageUrl: "https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=1920&q=80",
    timezone: "America/Cancun",
    currency: "MXN",
    language: "es-MX",
  },
  {
    id: "dubai-ae",
    city: "Dubai",
    country: "Emirados Arabes Unidos",
    countryCode: "AE",
    label: "Dubai, Emirados Arabes Unidos",
    aliases: ["dubai uae", "emirados", "eau"],
    coverImageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1920&q=80",
    timezone: "Asia/Dubai",
    currency: "AED",
    language: "ar-AE",
  },
  {
    id: "tokyo-jp",
    city: "Tokyo",
    country: "Japao",
    countryCode: "JP",
    label: "Tokyo, Japao",
    aliases: ["toquio", "tokio", "tokyo japan"],
    coverImageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1920&q=80",
    timezone: "Asia/Tokyo",
    currency: "JPY",
    language: "ja-JP",
  },
  {
    id: "brasilia-br",
    city: "Brasilia",
    country: "Brasil",
    countryCode: "BR",
    label: "Brasilia, Brasil",
    aliases: ["bsb", "capital federal"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "belo-horizonte-br",
    city: "Belo Horizonte",
    country: "Brasil",
    countryCode: "BR",
    label: "Belo Horizonte, Brasil",
    aliases: ["bh", "belo horizonte mg"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "curitiba-br",
    city: "Curitiba",
    country: "Brasil",
    countryCode: "BR",
    label: "Curitiba, Brasil",
    aliases: ["curitiba pr"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "recife-br",
    city: "Recife",
    country: "Brasil",
    countryCode: "BR",
    label: "Recife, Brasil",
    aliases: ["recife pe"],
    timezone: "America/Recife",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "fortaleza-br",
    city: "Fortaleza",
    country: "Brasil",
    countryCode: "BR",
    label: "Fortaleza, Brasil",
    aliases: ["fortaleza ce"],
    timezone: "America/Fortaleza",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "natal-br",
    city: "Natal",
    country: "Brasil",
    countryCode: "BR",
    label: "Natal, Brasil",
    aliases: ["natal rn"],
    timezone: "America/Fortaleza",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "joao-pessoa-br",
    city: "Joao Pessoa",
    country: "Brasil",
    countryCode: "BR",
    label: "Joao Pessoa, Brasil",
    aliases: ["joao pessoa pb"],
    timezone: "America/Fortaleza",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "maceio-br",
    city: "Maceio",
    country: "Brasil",
    countryCode: "BR",
    label: "Maceio, Brasil",
    aliases: ["maceio al"],
    timezone: "America/Maceio",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "porto-seguro-br",
    city: "Porto Seguro",
    country: "Brasil",
    countryCode: "BR",
    label: "Porto Seguro, Brasil",
    aliases: ["porto seguro ba"],
    timezone: "America/Bahia",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "balneario-camboriu-br",
    city: "Balneario Camboriu",
    country: "Brasil",
    countryCode: "BR",
    label: "Balneario Camboriu, Brasil",
    aliases: ["balneario", "bc", "camboriu"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "jericoacoara-br",
    city: "Jericoacoara",
    country: "Brasil",
    countryCode: "BR",
    label: "Jericoacoara, Brasil",
    aliases: ["jeri"],
    timezone: "America/Fortaleza",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "fernando-de-noronha-br",
    city: "Fernando de Noronha",
    country: "Brasil",
    countryCode: "BR",
    label: "Fernando de Noronha, Brasil",
    aliases: ["noronha"],
    timezone: "America/Noronha",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "bonito-br",
    city: "Bonito",
    country: "Brasil",
    countryCode: "BR",
    label: "Bonito, Brasil",
    aliases: ["bonito ms"],
    timezone: "America/Campo_Grande",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "manaus-br",
    city: "Manaus",
    country: "Brasil",
    countryCode: "BR",
    label: "Manaus, Brasil",
    aliases: ["manaus am"],
    timezone: "America/Manaus",
    currency: "BRL",
    language: "pt-BR",
  },
  {
    id: "mendoza-ar",
    city: "Mendoza",
    country: "Argentina",
    countryCode: "AR",
    label: "Mendoza, Argentina",
    aliases: ["mendoza ar"],
    timezone: "America/Argentina/Mendoza",
    currency: "ARS",
    language: "es-AR",
  },
  {
    id: "bariloche-ar",
    city: "Bariloche",
    country: "Argentina",
    countryCode: "AR",
    label: "Bariloche, Argentina",
    aliases: ["san carlos de bariloche"],
    timezone: "America/Argentina/Bariloche",
    currency: "ARS",
    language: "es-AR",
  },
  {
    id: "atacama-cl",
    city: "Atacama",
    country: "Chile",
    countryCode: "CL",
    label: "Atacama, Chile",
    aliases: ["deserto do atacama", "san pedro de atacama"],
    timezone: "America/Santiago",
    currency: "CLP",
    language: "es-CL",
  },
  {
    id: "lima-pe",
    city: "Lima",
    country: "Peru",
    countryCode: "PE",
    label: "Lima, Peru",
    aliases: ["lima peru"],
    timezone: "America/Lima",
    currency: "PEN",
    language: "es-PE",
  },
  {
    id: "cusco-pe",
    city: "Cusco",
    country: "Peru",
    countryCode: "PE",
    label: "Cusco, Peru",
    aliases: ["cusco peru", "machu picchu"],
    timezone: "America/Lima",
    currency: "PEN",
    language: "es-PE",
  },
  {
    id: "montevideu-uy",
    city: "Montevideu",
    country: "Uruguai",
    countryCode: "UY",
    label: "Montevideu, Uruguai",
    aliases: ["montevideo"],
    timezone: "America/Montevideo",
    currency: "UYU",
    language: "es-UY",
  },
  {
    id: "punta-del-este-uy",
    city: "Punta del Este",
    country: "Uruguai",
    countryCode: "UY",
    label: "Punta del Este, Uruguai",
    aliases: ["punta"],
    timezone: "America/Montevideo",
    currency: "UYU",
    language: "es-UY",
  },
  {
    id: "las-vegas-us",
    city: "Las Vegas",
    country: "Estados Unidos",
    countryCode: "US",
    label: "Las Vegas, Estados Unidos",
    aliases: ["vegas"],
    timezone: "America/Los_Angeles",
    currency: "USD",
    language: "en-US",
  },
  {
    id: "los-angeles-us",
    city: "Los Angeles",
    country: "Estados Unidos",
    countryCode: "US",
    label: "Los Angeles, Estados Unidos",
    aliases: ["la", "los angeles california"],
    timezone: "America/Los_Angeles",
    currency: "USD",
    language: "en-US",
  },
  {
    id: "san-francisco-us",
    city: "San Francisco",
    country: "Estados Unidos",
    countryCode: "US",
    label: "San Francisco, Estados Unidos",
    aliases: ["sf", "san francisco california"],
    timezone: "America/Los_Angeles",
    currency: "USD",
    language: "en-US",
  },
  {
    id: "chicago-us",
    city: "Chicago",
    country: "Estados Unidos",
    countryCode: "US",
    label: "Chicago, Estados Unidos",
    aliases: ["chicago illinois"],
    timezone: "America/Chicago",
    currency: "USD",
    language: "en-US",
  },
  {
    id: "washington-us",
    city: "Washington",
    country: "Estados Unidos",
    countryCode: "US",
    label: "Washington, Estados Unidos",
    aliases: ["washington dc", "dc"],
    timezone: "America/New_York",
    currency: "USD",
    language: "en-US",
  },
  {
    id: "boston-us",
    city: "Boston",
    country: "Estados Unidos",
    countryCode: "US",
    label: "Boston, Estados Unidos",
    aliases: ["boston massachusetts"],
    timezone: "America/New_York",
    currency: "USD",
    language: "en-US",
  },
  {
    id: "porto-pt",
    city: "Porto",
    country: "Portugal",
    countryCode: "PT",
    label: "Porto, Portugal",
    aliases: ["porto pt"],
    timezone: "Europe/Lisbon",
    currency: "EUR",
    language: "pt-PT",
  },
  {
    id: "barcelona-es",
    city: "Barcelona",
    country: "Espanha",
    countryCode: "ES",
    label: "Barcelona, Espanha",
    aliases: ["barcelona espanha"],
    timezone: "Europe/Madrid",
    currency: "EUR",
    language: "es-ES",
  },
  {
    id: "veneza-it",
    city: "Veneza",
    country: "Italia",
    countryCode: "IT",
    label: "Veneza, Italia",
    aliases: ["venice", "venezia"],
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  },
  {
    id: "florenca-it",
    city: "Florenca",
    country: "Italia",
    countryCode: "IT",
    label: "Florenca, Italia",
    aliases: ["florence", "firenze"],
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  },
  {
    id: "milao-it",
    city: "Milao",
    country: "Italia",
    countryCode: "IT",
    label: "Milao, Italia",
    aliases: ["milan", "milao italia"],
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  },
  {
    id: "amsterdam-nl",
    city: "Amsterdam",
    country: "Paises Baixos",
    countryCode: "NL",
    label: "Amsterdam, Paises Baixos",
    aliases: ["amsterdam", "holanda"],
    timezone: "Europe/Amsterdam",
    currency: "EUR",
    language: "nl-NL",
  },
  {
    id: "berlim-de",
    city: "Berlim",
    country: "Alemanha",
    countryCode: "DE",
    label: "Berlim, Alemanha",
    aliases: ["berlin"],
    timezone: "Europe/Berlin",
    currency: "EUR",
    language: "de-DE",
  },
  {
    id: "munique-de",
    city: "Munique",
    country: "Alemanha",
    countryCode: "DE",
    label: "Munique, Alemanha",
    aliases: ["munich"],
    timezone: "Europe/Berlin",
    currency: "EUR",
    language: "de-DE",
  },
  {
    id: "praga-cz",
    city: "Praga",
    country: "Republica Tcheca",
    countryCode: "CZ",
    label: "Praga, Republica Tcheca",
    aliases: ["prague"],
    timezone: "Europe/Prague",
    currency: "CZK",
    language: "cs-CZ",
  },
  {
    id: "viena-at",
    city: "Viena",
    country: "Austria",
    countryCode: "AT",
    label: "Viena, Austria",
    aliases: ["vienna"],
    timezone: "Europe/Vienna",
    currency: "EUR",
    language: "de-AT",
  },
  {
    id: "zurique-ch",
    city: "Zurique",
    country: "Suica",
    countryCode: "CH",
    label: "Zurique, Suica",
    aliases: ["zurich"],
    timezone: "Europe/Zurich",
    currency: "CHF",
    language: "de-CH",
  },
  {
    id: "genebra-ch",
    city: "Genebra",
    country: "Suica",
    countryCode: "CH",
    label: "Genebra, Suica",
    aliases: ["geneva"],
    timezone: "Europe/Zurich",
    currency: "CHF",
    language: "fr-CH",
  },
  {
    id: "bruxelas-be",
    city: "Bruxelas",
    country: "Belgica",
    countryCode: "BE",
    label: "Bruxelas, Belgica",
    aliases: ["brussels"],
    timezone: "Europe/Brussels",
    currency: "EUR",
    language: "fr-BE",
  },
  {
    id: "atenas-gr",
    city: "Atenas",
    country: "Grecia",
    countryCode: "GR",
    label: "Atenas, Grecia",
    aliases: ["athens"],
    timezone: "Europe/Athens",
    currency: "EUR",
    language: "el-GR",
  },
  {
    id: "abu-dhabi-ae",
    city: "Abu Dhabi",
    country: "Emirados Arabes Unidos",
    countryCode: "AE",
    label: "Abu Dhabi, Emirados Arabes Unidos",
    aliases: ["abu dhabi uae"],
    timezone: "Asia/Dubai",
    currency: "AED",
    language: "ar-AE",
  },
  {
    id: "kyoto-jp",
    city: "Kyoto",
    country: "Japao",
    countryCode: "JP",
    label: "Kyoto, Japao",
    aliases: ["quioto"],
    timezone: "Asia/Tokyo",
    currency: "JPY",
    language: "ja-JP",
  },
  {
    id: "osaka-jp",
    city: "Osaka",
    country: "Japao",
    countryCode: "JP",
    label: "Osaka, Japao",
    aliases: ["osaka japan"],
    timezone: "Asia/Tokyo",
    currency: "JPY",
    language: "ja-JP",
  },
  {
    id: "seoul-kr",
    city: "Seoul",
    country: "Coreia do Sul",
    countryCode: "KR",
    label: "Seoul, Coreia do Sul",
    aliases: ["seul"],
    timezone: "Asia/Seoul",
    currency: "KRW",
    language: "ko-KR",
  },
  {
    id: "bangkok-th",
    city: "Bangkok",
    country: "Tailandia",
    countryCode: "TH",
    label: "Bangkok, Tailandia",
    aliases: ["bangkok thailand"],
    timezone: "Asia/Bangkok",
    currency: "THB",
    language: "th-TH",
  },
  {
    id: "phuket-th",
    city: "Phuket",
    country: "Tailandia",
    countryCode: "TH",
    label: "Phuket, Tailandia",
    aliases: ["phuket thailand"],
    timezone: "Asia/Bangkok",
    currency: "THB",
    language: "th-TH",
  },
  {
    id: "bali-id",
    city: "Bali",
    country: "Indonesia",
    countryCode: "ID",
    label: "Bali, Indonesia",
    aliases: ["ubud", "seminyak"],
    timezone: "Asia/Makassar",
    currency: "IDR",
    language: "id-ID",
  },
  {
    id: "cidade-do-mexico-mx",
    city: "Cidade do Mexico",
    country: "Mexico",
    countryCode: "MX",
    label: "Cidade do Mexico, Mexico",
    aliases: ["mexico city", "cdmx"],
    timezone: "America/Mexico_City",
    currency: "MXN",
    language: "es-MX",
  },
  {
    id: "punta-cana-do",
    city: "Punta Cana",
    country: "Republica Dominicana",
    countryCode: "DO",
    label: "Punta Cana, Republica Dominicana",
    aliases: ["punta cana republica dominicana"],
    timezone: "America/Santo_Domingo",
    currency: "DOP",
    language: "es-DO",
  },
  {
    id: "cartagena-co",
    city: "Cartagena",
    country: "Colombia",
    countryCode: "CO",
    label: "Cartagena, Colombia",
    aliases: ["cartagena colombia"],
    timezone: "America/Bogota",
    currency: "COP",
    language: "es-CO",
  },
  {
    id: "bogota-co",
    city: "Bogota",
    country: "Colombia",
    countryCode: "CO",
    label: "Bogota, Colombia",
    aliases: ["bogota colombia"],
    timezone: "America/Bogota",
    currency: "COP",
    language: "es-CO",
  },
  {
    id: "toronto-ca",
    city: "Toronto",
    country: "Canada",
    countryCode: "CA",
    label: "Toronto, Canada",
    aliases: ["toronto canada"],
    timezone: "America/Toronto",
    currency: "CAD",
    language: "en-CA",
  },
  {
    id: "vancouver-ca",
    city: "Vancouver",
    country: "Canada",
    countryCode: "CA",
    label: "Vancouver, Canada",
    aliases: ["vancouver canada"],
    timezone: "America/Vancouver",
    currency: "CAD",
    language: "en-CA",
  },
  {
    id: "sydney-au",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    label: "Sydney, Australia",
    aliases: ["sidney"],
    timezone: "Australia/Sydney",
    currency: "AUD",
    language: "en-AU",
  },
  {
    id: "melbourne-au",
    city: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    label: "Melbourne, Australia",
    aliases: ["melbourne australia"],
    timezone: "Australia/Melbourne",
    currency: "AUD",
    language: "en-AU",
  },
  {
    id: "cape-town-za",
    city: "Cape Town",
    country: "Africa do Sul",
    countryCode: "ZA",
    label: "Cape Town, Africa do Sul",
    aliases: ["cidade do cabo"],
    timezone: "Africa/Johannesburg",
    currency: "ZAR",
    language: "en-ZA",
  },
  {
    id: "marrakech-ma",
    city: "Marrakech",
    country: "Marrocos",
    countryCode: "MA",
    label: "Marrakech, Marrocos",
    aliases: ["marrakesh"],
    timezone: "Africa/Casablanca",
    currency: "MAD",
    language: "ar-MA",
  },
]

export function normalizeDestinationText(value?: string | null) {
  return (value ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9,\s-]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
}

function getSearchTokens(option: DestinationOption) {
  return [
    option.id,
    option.city,
    option.country,
    option.countryCode,
    option.label,
    ...option.aliases,
  ].map((value) => normalizeDestinationText(value))
}

export function getDestinationOptionById(id?: string | null) {
  if (!id) return null
  return DESTINATION_CATALOG.find((option) => option.id === id) ?? null
}

export function searchDestinationOptions(query: string, limit = 6) {
  const normalizedQuery = normalizeDestinationText(query)
  if (!normalizedQuery) {
    return DESTINATION_CATALOG.slice(0, limit)
  }

  return [...DESTINATION_CATALOG]
    .map((option) => {
      const tokens = getSearchTokens(option)
      const score = tokens.reduce((best, token) => {
        if (token === normalizedQuery) return Math.max(best, 100)
        if (token.startsWith(normalizedQuery)) return Math.max(best, 80)
        if (token.includes(normalizedQuery)) return Math.max(best, 60)
        if (normalizedQuery.includes(token)) return Math.max(best, 40)
        return best
      }, 0)

      return { option, score }
    })
    .filter((entry) => entry.score > 0)
    .sort((left, right) => right.score - left.score || left.option.label.localeCompare(right.option.label))
    .slice(0, limit)
    .map((entry) => entry.option)
}

export function resolveDestinationOption(input?: string | null, selectedId?: string | null) {
  const selected = getDestinationOptionById(selectedId)
  if (selected) return selected

  const normalizedInput = normalizeDestinationText(input)
  if (!normalizedInput) return null

  const exact = DESTINATION_CATALOG.find((option) =>
    getSearchTokens(option).some((token) => token === normalizedInput)
  )
  if (exact) return exact

  return null
}

export function resolveDestinationInput(input: string, selectedId?: string | null): ResolvedDestinationInput {
  const matchedOption = resolveDestinationOption(input, selectedId)
  if (matchedOption) {
    return {
      id: matchedOption.id,
      label: matchedOption.label,
      city: matchedOption.city,
      country: matchedOption.country,
      countryCode: matchedOption.countryCode,
      coverImageUrl: matchedOption.coverImageUrl ?? null,
      timezone: matchedOption.timezone ?? null,
      currency: matchedOption.currency ?? null,
      language: matchedOption.language ?? null,
      matchedCatalog: true,
    }
  }

  const normalizedLabel = input.trim()
  const parts = normalizedLabel.split(",").map((part) => part.trim()).filter(Boolean)

  return {
    id: null,
    label: normalizedLabel,
    city: parts[0] || normalizedLabel || null,
    country: parts.length > 1 ? parts[parts.length - 1] : null,
    countryCode: null,
    coverImageUrl: null,
    timezone: null,
    currency: null,
    language: null,
    matchedCatalog: false,
  }
}
