export type DestinationOption = {
  id: string
  city: string
  country: string
  countryCode: string
  label: string
  aliases: string[]
  coverImageUrl?: string
  timezone?: string
  currency?: string
  language?: string
}

export type ResolvedDestinationInput = {
  id: string | null
  label: string
  city: string | null
  country: string | null
  countryCode: string | null
  coverImageUrl: string | null
  timezone: string | null
  currency: string | null
  language: string | null
  matchedCatalog: boolean
}

type DestinationSeed = Omit<DestinationOption, "label">

function createDestination(seed: DestinationSeed): DestinationOption {
  const label = seed.city === seed.country ? seed.city : `${seed.city}, ${seed.country}`
  return {
    ...seed,
    label,
  }
}

export const DESTINATION_CATALOG: DestinationOption[] = [
  // Brasil
  createDestination({
    id: "rio-de-janeiro-br",
    city: "Rio de Janeiro",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["rio", "rj", "cidade maravilhosa"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "sao-paulo-br",
    city: "São Paulo",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["sao paulo", "sp", "capital paulista"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "salvador-br",
    city: "Salvador",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["salvador bahia", "ssa"],
    timezone: "America/Bahia",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "fortaleza-br",
    city: "Fortaleza",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["fortaleza ce"],
    timezone: "America/Fortaleza",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "recife-br",
    city: "Recife",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["recife pe"],
    timezone: "America/Recife",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "porto-de-galinhas-br",
    city: "Porto de Galinhas",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["porto de galinhas pe", "ipojuca"],
    timezone: "America/Recife",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "maceio-br",
    city: "Maceió",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["maceio", "maceio al"],
    timezone: "America/Maceio",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "natal-br",
    city: "Natal",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["natal rn"],
    timezone: "America/Fortaleza",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "florianopolis-br",
    city: "Florianópolis",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["florianopolis", "floripa", "florianopolis sc"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "gramado-br",
    city: "Gramado",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["serra gaúcha", "serra gaucha", "canela"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "foz-do-iguacu-br",
    city: "Foz do Iguaçu",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["foz do iguacu", "foz", "iguacu", "cataratas"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "bonito-br",
    city: "Bonito",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["bonito ms"],
    timezone: "America/Campo_Grande",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "jericoacoara-br",
    city: "Jericoacoara",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["jeri"],
    timezone: "America/Fortaleza",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "fernando-de-noronha-br",
    city: "Fernando de Noronha",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["noronha"],
    timezone: "America/Noronha",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "brasilia-br",
    city: "Brasília",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["brasilia", "bsb", "capital federal"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "belo-horizonte-br",
    city: "Belo Horizonte",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["bh", "belo horizonte mg"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "curitiba-br",
    city: "Curitiba",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["curitiba pr"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "manaus-br",
    city: "Manaus",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["manaus am", "amazônia", "amazonia"],
    timezone: "America/Manaus",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "porto-seguro-br",
    city: "Porto Seguro",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["porto seguro ba", "arraial d ajuda", "trancoso"],
    timezone: "America/Bahia",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "balneario-camboriu-br",
    city: "Balneário Camboriú",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["balneario camboriu", "balneário", "bc", "camboriu"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "joao-pessoa-br",
    city: "João Pessoa",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["joao pessoa", "joao pessoa pb"],
    timezone: "America/Fortaleza",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "ilhabela-br",
    city: "Ilhabela",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["ilhabela sp"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "buzios-br",
    city: "Búzios",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["buzios", "armação dos búzios", "armacao dos buzios"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "paraty-br",
    city: "Paraty",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["parati", "paraty rj"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "campos-do-jordao-br",
    city: "Campos do Jordão",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["campos do jordao", "serra da mantiqueira"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "maragogi-br",
    city: "Maragogi",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["maragogi al", "galés", "gales"],
    timezone: "America/Maceio",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "lencois-maranhenses-br",
    city: "Lençóis Maranhenses",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["lencois maranhenses", "barreirinhas", "santo amaro do maranhao"],
    timezone: "America/Fortaleza",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "sao-luis-br",
    city: "São Luís",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["sao luis", "sao luis ma"],
    timezone: "America/Fortaleza",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "porto-alegre-br",
    city: "Porto Alegre",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["porto alegre rs"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),
  createDestination({
    id: "goiania-br",
    city: "Goiânia",
    country: "Brasil",
    countryCode: "BR",
    aliases: ["goiania", "goiânia go"],
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
  }),

  // América do Sul
  createDestination({
    id: "buenos-aires-ar",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    aliases: ["buenos aires ar", "capital argentina"],
    timezone: "America/Argentina/Buenos_Aires",
    currency: "ARS",
    language: "es-AR",
  }),
  createDestination({
    id: "bariloche-ar",
    city: "Bariloche",
    country: "Argentina",
    countryCode: "AR",
    aliases: ["san carlos de bariloche"],
    timezone: "America/Argentina/Bariloche",
    currency: "ARS",
    language: "es-AR",
  }),
  createDestination({
    id: "mendoza-ar",
    city: "Mendoza",
    country: "Argentina",
    countryCode: "AR",
    aliases: ["vinícolas mendoza", "vinicolas mendoza"],
    timezone: "America/Argentina/Mendoza",
    currency: "ARS",
    language: "es-AR",
  }),
  createDestination({
    id: "ushuaia-ar",
    city: "Ushuaia",
    country: "Argentina",
    countryCode: "AR",
    aliases: ["fim do mundo", "terra do fogo"],
    timezone: "America/Argentina/Ushuaia",
    currency: "ARS",
    language: "es-AR",
  }),
  createDestination({
    id: "el-calafate-ar",
    city: "El Calafate",
    country: "Argentina",
    countryCode: "AR",
    aliases: ["perito moreno", "patagônia argentina", "patagonia argentina"],
    timezone: "America/Argentina/Rio_Gallegos",
    currency: "ARS",
    language: "es-AR",
  }),
  createDestination({
    id: "santiago-cl",
    city: "Santiago",
    country: "Chile",
    countryCode: "CL",
    aliases: ["santiago do chile", "scl"],
    timezone: "America/Santiago",
    currency: "CLP",
    language: "es-CL",
  }),
  createDestination({
    id: "atacama-cl",
    city: "Atacama",
    country: "Chile",
    countryCode: "CL",
    aliases: ["deserto do atacama", "deserto de atacama", "san pedro de atacama"],
    timezone: "America/Santiago",
    currency: "CLP",
    language: "es-CL",
  }),
  createDestination({
    id: "vina-del-mar-cl",
    city: "Viña del Mar",
    country: "Chile",
    countryCode: "CL",
    aliases: ["vina del mar", "valparaiso", "valparaíso"],
    timezone: "America/Santiago",
    currency: "CLP",
    language: "es-CL",
  }),
  createDestination({
    id: "montevideu-uy",
    city: "Montevidéu",
    country: "Uruguai",
    countryCode: "UY",
    aliases: ["montevideu", "montevideo"],
    timezone: "America/Montevideo",
    currency: "UYU",
    language: "es-UY",
  }),
  createDestination({
    id: "punta-del-este-uy",
    city: "Punta del Este",
    country: "Uruguai",
    countryCode: "UY",
    aliases: ["punta", "punta del este uruguai"],
    timezone: "America/Montevideo",
    currency: "UYU",
    language: "es-UY",
  }),
  createDestination({
    id: "lima-pe",
    city: "Lima",
    country: "Peru",
    countryCode: "PE",
    aliases: ["lima peru"],
    timezone: "America/Lima",
    currency: "PEN",
    language: "es-PE",
  }),
  createDestination({
    id: "cusco-pe",
    city: "Cusco",
    country: "Peru",
    countryCode: "PE",
    aliases: ["cuzco", "cusco peru"],
    timezone: "America/Lima",
    currency: "PEN",
    language: "es-PE",
  }),
  createDestination({
    id: "machu-picchu-pe",
    city: "Machu Picchu",
    country: "Peru",
    countryCode: "PE",
    aliases: ["machu picchu peru", "aguas calientes"],
    timezone: "America/Lima",
    currency: "PEN",
    language: "es-PE",
  }),
  createDestination({
    id: "quito-ec",
    city: "Quito",
    country: "Equador",
    countryCode: "EC",
    aliases: ["quito ecuador"],
    timezone: "America/Guayaquil",
    currency: "USD",
    language: "es-EC",
  }),
  createDestination({
    id: "galapagos-ec",
    city: "Galápagos",
    country: "Equador",
    countryCode: "EC",
    aliases: ["galapagos", "ilhas galápagos", "ilhas galapagos"],
    timezone: "Pacific/Galapagos",
    currency: "USD",
    language: "es-EC",
  }),
  createDestination({
    id: "medellin-co",
    city: "Medellín",
    country: "Colômbia",
    countryCode: "CO",
    aliases: ["medellin", "medellin colombia"],
    timezone: "America/Bogota",
    currency: "COP",
    language: "es-CO",
  }),
  createDestination({
    id: "bogota-co",
    city: "Bogotá",
    country: "Colômbia",
    countryCode: "CO",
    aliases: ["bogota", "bogota colombia"],
    timezone: "America/Bogota",
    currency: "COP",
    language: "es-CO",
  }),
  createDestination({
    id: "cartagena-co",
    city: "Cartagena",
    country: "Colômbia",
    countryCode: "CO",
    aliases: ["cartagena colombia", "cartagena das índias", "cartagena das indias"],
    timezone: "America/Bogota",
    currency: "COP",
    language: "es-CO",
  }),
  createDestination({
    id: "san-andres-co",
    city: "San Andrés",
    country: "Colômbia",
    countryCode: "CO",
    aliases: ["san andres", "san andrés", "caribe colombiano"],
    timezone: "America/Bogota",
    currency: "COP",
    language: "es-CO",
  }),

  // Caribe
  createDestination({
    id: "aruba-aw",
    city: "Aruba",
    country: "Aruba",
    countryCode: "AW",
    aliases: ["aruba", "oranjestad", "caribe"],
    timezone: "America/Aruba",
    currency: "AWG",
    language: "nl-AW",
  }),
  createDestination({
    id: "curacao-cw",
    city: "Curaçao",
    country: "Curaçao",
    countryCode: "CW",
    aliases: ["curacao", "willemstad", "caribe holandês", "caribe holandes"],
    timezone: "America/Curacao",
    currency: "ANG",
    language: "nl-CW",
  }),
  createDestination({
    id: "punta-cana-do",
    city: "Punta Cana",
    country: "República Dominicana",
    countryCode: "DO",
    aliases: ["punta cana republica dominicana", "punta cana dominicana"],
    timezone: "America/Santo_Domingo",
    currency: "DOP",
    language: "es-DO",
  }),
  createDestination({
    id: "cancun-mx",
    city: "Cancún",
    country: "México",
    countryCode: "MX",
    aliases: ["cancun", "cancun mexico"],
    timezone: "America/Cancun",
    currency: "MXN",
    language: "es-MX",
  }),
  createDestination({
    id: "tulum-mx",
    city: "Tulum",
    country: "México",
    countryCode: "MX",
    aliases: ["riviera maya", "tulum mexico"],
    timezone: "America/Cancun",
    currency: "MXN",
    language: "es-MX",
  }),
  createDestination({
    id: "bahamas-bs",
    city: "Bahamas",
    country: "Bahamas",
    countryCode: "BS",
    aliases: ["nassau", "exuma"],
    timezone: "America/Nassau",
    currency: "BSD",
    language: "en-BS",
  }),
  createDestination({
    id: "jamaica-jm",
    city: "Jamaica",
    country: "Jamaica",
    countryCode: "JM",
    aliases: ["montego bay", "ocho rios", "kingston jamaica"],
    timezone: "America/Jamaica",
    currency: "JMD",
    language: "en-JM",
  }),
  createDestination({
    id: "barbados-bb",
    city: "Barbados",
    country: "Barbados",
    countryCode: "BB",
    aliases: ["bridgetown"],
    timezone: "America/Barbados",
    currency: "BBD",
    language: "en-BB",
  }),
  createDestination({
    id: "san-juan-pr",
    city: "San Juan",
    country: "Porto Rico",
    countryCode: "PR",
    aliases: ["puerto rico", "porto rico caribe"],
    timezone: "America/Puerto_Rico",
    currency: "USD",
    language: "es-PR",
  }),
  createDestination({
    id: "havana-cu",
    city: "Havana",
    country: "Cuba",
    countryCode: "CU",
    aliases: ["havanna", "havana cuba", "la habana"],
    timezone: "America/Havana",
    currency: "CUP",
    language: "es-CU",
  }),
  createDestination({
    id: "turks-and-caicos-tc",
    city: "Turks and Caicos",
    country: "Turks and Caicos",
    countryCode: "TC",
    aliases: ["providenciales", "turks caicos"],
    timezone: "America/Grand_Turk",
    currency: "USD",
    language: "en-TC",
  }),
  createDestination({
    id: "st-maarten-sx",
    city: "St. Maarten",
    country: "St. Maarten",
    countryCode: "SX",
    aliases: ["saint maarten", "sint maarten"],
    timezone: "America/Lower_Princes",
    currency: "ANG",
    language: "en-SX",
  }),

  // Estados Unidos
  createDestination({
    id: "orlando-us",
    city: "Orlando",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["orlando florida", "disney", "universal orlando"],
    timezone: "America/New_York",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "miami-us",
    city: "Miami",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["miami florida", "south beach"],
    timezone: "America/New_York",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "nova-york-us",
    city: "Nova York",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["new york", "nyc", "nova iorque"],
    timezone: "America/New_York",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "las-vegas-us",
    city: "Las Vegas",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["vegas", "las vegas nevada"],
    timezone: "America/Los_Angeles",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "los-angeles-us",
    city: "Los Angeles",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["los angeles", "la", "califórnia", "california"],
    timezone: "America/Los_Angeles",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "san-francisco-us",
    city: "San Francisco",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["sf", "golden gate", "san francisco california"],
    timezone: "America/Los_Angeles",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "chicago-us",
    city: "Chicago",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["chicago illinois"],
    timezone: "America/Chicago",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "washington-dc-us",
    city: "Washington, D.C.",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["washington dc", "dc", "capital americana"],
    timezone: "America/New_York",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "boston-us",
    city: "Boston",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["boston massachusetts"],
    timezone: "America/New_York",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "san-diego-us",
    city: "San Diego",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["san diego california"],
    timezone: "America/Los_Angeles",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "seattle-us",
    city: "Seattle",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["seattle washington"],
    timezone: "America/Los_Angeles",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "honolulu-us",
    city: "Honolulu",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["havaí", "hawaii", "oahu"],
    timezone: "Pacific/Honolulu",
    currency: "USD",
    language: "en-US",
  }),
  createDestination({
    id: "maui-us",
    city: "Maui",
    country: "Estados Unidos",
    countryCode: "US",
    aliases: ["havaí maui", "hawaii maui"],
    timezone: "Pacific/Honolulu",
    currency: "USD",
    language: "en-US",
  }),

  // Europa
  createDestination({
    id: "lisboa-pt",
    city: "Lisboa",
    country: "Portugal",
    countryCode: "PT",
    aliases: ["lisbon", "lisboa pt"],
    timezone: "Europe/Lisbon",
    currency: "EUR",
    language: "pt-PT",
  }),
  createDestination({
    id: "porto-pt",
    city: "Porto",
    country: "Portugal",
    countryCode: "PT",
    aliases: ["porto pt", "oporto"],
    timezone: "Europe/Lisbon",
    currency: "EUR",
    language: "pt-PT",
  }),
  createDestination({
    id: "paris-fr",
    city: "Paris",
    country: "França",
    countryCode: "FR",
    aliases: ["paris france", "cidade luz"],
    timezone: "Europe/Paris",
    currency: "EUR",
    language: "fr-FR",
  }),
  createDestination({
    id: "londres-gb",
    city: "Londres",
    country: "Reino Unido",
    countryCode: "GB",
    aliases: ["london", "londres uk"],
    timezone: "Europe/London",
    currency: "GBP",
    language: "en-GB",
  }),
  createDestination({
    id: "roma-it",
    city: "Roma",
    country: "Itália",
    countryCode: "IT",
    aliases: ["rome", "roma italia"],
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  }),
  createDestination({
    id: "veneza-it",
    city: "Veneza",
    country: "Itália",
    countryCode: "IT",
    aliases: ["venezia", "venice"],
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  }),
  createDestination({
    id: "milao-it",
    city: "Milão",
    country: "Itália",
    countryCode: "IT",
    aliases: ["milao", "milan"],
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  }),
  createDestination({
    id: "florenca-it",
    city: "Florença",
    country: "Itália",
    countryCode: "IT",
    aliases: ["florenca", "florence", "firenze"],
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  }),
  createDestination({
    id: "napoles-it",
    city: "Nápoles",
    country: "Itália",
    countryCode: "IT",
    aliases: ["napoles", "napoli", "amalfi"],
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  }),
  createDestination({
    id: "madrid-es",
    city: "Madrid",
    country: "Espanha",
    countryCode: "ES",
    aliases: ["madrid espana"],
    timezone: "Europe/Madrid",
    currency: "EUR",
    language: "es-ES",
  }),
  createDestination({
    id: "barcelona-es",
    city: "Barcelona",
    country: "Espanha",
    countryCode: "ES",
    aliases: ["barcelona espanha", "barcelona espana"],
    timezone: "Europe/Madrid",
    currency: "EUR",
    language: "es-ES",
  }),
  createDestination({
    id: "sevilha-es",
    city: "Sevilha",
    country: "Espanha",
    countryCode: "ES",
    aliases: ["sevilla"],
    timezone: "Europe/Madrid",
    currency: "EUR",
    language: "es-ES",
  }),
  createDestination({
    id: "amsterdam-nl",
    city: "Amsterdam",
    country: "Holanda",
    countryCode: "NL",
    aliases: ["amsterdã", "amsterda", "netherlands"],
    timezone: "Europe/Amsterdam",
    currency: "EUR",
    language: "nl-NL",
  }),
  createDestination({
    id: "berlim-de",
    city: "Berlim",
    country: "Alemanha",
    countryCode: "DE",
    aliases: ["berlin"],
    timezone: "Europe/Berlin",
    currency: "EUR",
    language: "de-DE",
  }),
  createDestination({
    id: "munique-de",
    city: "Munique",
    country: "Alemanha",
    countryCode: "DE",
    aliases: ["munchen", "munich"],
    timezone: "Europe/Berlin",
    currency: "EUR",
    language: "de-DE",
  }),
  createDestination({
    id: "zurique-ch",
    city: "Zurique",
    country: "Suíça",
    countryCode: "CH",
    aliases: ["zurich", "zurique suica", "zurique suíça"],
    timezone: "Europe/Zurich",
    currency: "CHF",
    language: "de-CH",
  }),
  createDestination({
    id: "genebra-ch",
    city: "Genebra",
    country: "Suíça",
    countryCode: "CH",
    aliases: ["geneva", "genebra suica", "genebra suíça"],
    timezone: "Europe/Zurich",
    currency: "CHF",
    language: "fr-CH",
  }),
  createDestination({
    id: "praga-cz",
    city: "Praga",
    country: "República Tcheca",
    countryCode: "CZ",
    aliases: ["prague", "praga republica tcheca"],
    timezone: "Europe/Prague",
    currency: "CZK",
    language: "cs-CZ",
  }),
  createDestination({
    id: "viena-at",
    city: "Viena",
    country: "Áustria",
    countryCode: "AT",
    aliases: ["vienna"],
    timezone: "Europe/Vienna",
    currency: "EUR",
    language: "de-AT",
  }),
  createDestination({
    id: "bruxelas-be",
    city: "Bruxelas",
    country: "Bélgica",
    countryCode: "BE",
    aliases: ["brussels"],
    timezone: "Europe/Brussels",
    currency: "EUR",
    language: "fr-BE",
  }),
  createDestination({
    id: "atenas-gr",
    city: "Atenas",
    country: "Grécia",
    countryCode: "GR",
    aliases: ["athens"],
    timezone: "Europe/Athens",
    currency: "EUR",
    language: "el-GR",
  }),
  createDestination({
    id: "santorini-gr",
    city: "Santorini",
    country: "Grécia",
    countryCode: "GR",
    aliases: ["thira", "ilha santorini"],
    timezone: "Europe/Athens",
    currency: "EUR",
    language: "el-GR",
  }),
  createDestination({
    id: "mykonos-gr",
    city: "Mykonos",
    country: "Grécia",
    countryCode: "GR",
    aliases: ["ilha mykonos"],
    timezone: "Europe/Athens",
    currency: "EUR",
    language: "el-GR",
  }),
  createDestination({
    id: "dublin-ie",
    city: "Dublin",
    country: "Irlanda",
    countryCode: "IE",
    aliases: ["dublin ireland"],
    timezone: "Europe/Dublin",
    currency: "EUR",
    language: "en-IE",
  }),
  createDestination({
    id: "edimburgo-gb",
    city: "Edimburgo",
    country: "Reino Unido",
    countryCode: "GB",
    aliases: ["edinburgh", "escócia", "escocia"],
    timezone: "Europe/London",
    currency: "GBP",
    language: "en-GB",
  }),
  createDestination({
    id: "copenhague-dk",
    city: "Copenhague",
    country: "Dinamarca",
    countryCode: "DK",
    aliases: ["copenhagen"],
    timezone: "Europe/Copenhagen",
    currency: "DKK",
    language: "da-DK",
  }),
  createDestination({
    id: "istambul-tr",
    city: "Istambul",
    country: "Turquia",
    countryCode: "TR",
    aliases: ["istanbul", "constantinopla"],
    timezone: "Europe/Istanbul",
    currency: "TRY",
    language: "tr-TR",
  }),

  // Oriente Médio
  createDestination({
    id: "dubai-ae",
    city: "Dubai",
    country: "Emirados Árabes Unidos",
    countryCode: "AE",
    aliases: ["dubai uae", "emirados", "eau"],
    timezone: "Asia/Dubai",
    currency: "AED",
    language: "ar-AE",
  }),
  createDestination({
    id: "abu-dhabi-ae",
    city: "Abu Dhabi",
    country: "Emirados Árabes Unidos",
    countryCode: "AE",
    aliases: ["abu dhabi uae"],
    timezone: "Asia/Dubai",
    currency: "AED",
    language: "ar-AE",
  }),
  createDestination({
    id: "doha-qa",
    city: "Doha",
    country: "Catar",
    countryCode: "QA",
    aliases: ["doha qatar", "catar"],
    timezone: "Asia/Qatar",
    currency: "QAR",
    language: "ar-QA",
  }),
  createDestination({
    id: "qatar-qa",
    city: "Catar",
    country: "Catar",
    countryCode: "QA",
    aliases: ["qatar"],
    timezone: "Asia/Qatar",
    currency: "QAR",
    language: "ar-QA",
  }),
  createDestination({
    id: "jerusalem-il",
    city: "Jerusalém",
    country: "Israel",
    countryCode: "IL",
    aliases: ["jerusalem", "jerusalen"],
    timezone: "Asia/Jerusalem",
    currency: "ILS",
    language: "he-IL",
  }),
  createDestination({
    id: "tel-aviv-il",
    city: "Tel Aviv",
    country: "Israel",
    countryCode: "IL",
    aliases: ["tel aviv israel"],
    timezone: "Asia/Jerusalem",
    currency: "ILS",
    language: "he-IL",
  }),
  createDestination({
    id: "muscat-om",
    city: "Mascate",
    country: "Omã",
    countryCode: "OM",
    aliases: ["muscat", "oman"],
    timezone: "Asia/Muscat",
    currency: "OMR",
    language: "ar-OM",
  }),
  createDestination({
    id: "petra-jo",
    city: "Petra",
    country: "Jordânia",
    countryCode: "JO",
    aliases: ["jordania", "jordânia", "wadi musa"],
    timezone: "Asia/Amman",
    currency: "JOD",
    language: "ar-JO",
  }),

  // Ásia
  createDestination({
    id: "toquio-jp",
    city: "Tóquio",
    country: "Japão",
    countryCode: "JP",
    aliases: ["toquio", "tokyo", "tokio"],
    timezone: "Asia/Tokyo",
    currency: "JPY",
    language: "ja-JP",
  }),
  createDestination({
    id: "kyoto-jp",
    city: "Kyoto",
    country: "Japão",
    countryCode: "JP",
    aliases: ["quioto", "kyoto japan"],
    timezone: "Asia/Tokyo",
    currency: "JPY",
    language: "ja-JP",
  }),
  createDestination({
    id: "osaka-jp",
    city: "Osaka",
    country: "Japão",
    countryCode: "JP",
    aliases: ["osaka japan"],
    timezone: "Asia/Tokyo",
    currency: "JPY",
    language: "ja-JP",
  }),
  createDestination({
    id: "seul-kr",
    city: "Seul",
    country: "Coreia do Sul",
    countryCode: "KR",
    aliases: ["seoul", "coreia do sul"],
    timezone: "Asia/Seoul",
    currency: "KRW",
    language: "ko-KR",
  }),
  createDestination({
    id: "bangkok-th",
    city: "Bangkok",
    country: "Tailândia",
    countryCode: "TH",
    aliases: ["bangkok thailand", "tailandia", "tailândia"],
    timezone: "Asia/Bangkok",
    currency: "THB",
    language: "th-TH",
  }),
  createDestination({
    id: "phuket-th",
    city: "Phuket",
    country: "Tailândia",
    countryCode: "TH",
    aliases: ["phuket thailand"],
    timezone: "Asia/Bangkok",
    currency: "THB",
    language: "th-TH",
  }),
  createDestination({
    id: "chiang-mai-th",
    city: "Chiang Mai",
    country: "Tailândia",
    countryCode: "TH",
    aliases: ["chiang mai thailand"],
    timezone: "Asia/Bangkok",
    currency: "THB",
    language: "th-TH",
  }),
  createDestination({
    id: "tailandia-th",
    city: "Tailândia",
    country: "Tailândia",
    countryCode: "TH",
    aliases: ["tailandia", "thailand"],
    timezone: "Asia/Bangkok",
    currency: "THB",
    language: "th-TH",
  }),
  createDestination({
    id: "bali-id",
    city: "Bali",
    country: "Indonésia",
    countryCode: "ID",
    aliases: ["ubud", "seminyak", "nusa dua"],
    timezone: "Asia/Makassar",
    currency: "IDR",
    language: "id-ID",
  }),
  createDestination({
    id: "singapura-sg",
    city: "Singapura",
    country: "Singapura",
    countryCode: "SG",
    aliases: ["singapore"],
    timezone: "Asia/Singapore",
    currency: "SGD",
    language: "en-SG",
  }),
  createDestination({
    id: "hong-kong-hk",
    city: "Hong Kong",
    country: "Hong Kong",
    countryCode: "HK",
    aliases: ["hong kong china"],
    timezone: "Asia/Hong_Kong",
    currency: "HKD",
    language: "zh-HK",
  }),
  createDestination({
    id: "pequim-cn",
    city: "Pequim",
    country: "China",
    countryCode: "CN",
    aliases: ["beijing"],
    timezone: "Asia/Shanghai",
    currency: "CNY",
    language: "zh-CN",
  }),
  createDestination({
    id: "xangai-cn",
    city: "Xangai",
    country: "China",
    countryCode: "CN",
    aliases: ["shanghai"],
    timezone: "Asia/Shanghai",
    currency: "CNY",
    language: "zh-CN",
  }),
  createDestination({
    id: "hanoi-vn",
    city: "Hanói",
    country: "Vietnã",
    countryCode: "VN",
    aliases: ["hanoi", "hanoi vietnam"],
    timezone: "Asia/Ho_Chi_Minh",
    currency: "VND",
    language: "vi-VN",
  }),
  createDestination({
    id: "ho-chi-minh-vn",
    city: "Ho Chi Minh",
    country: "Vietnã",
    countryCode: "VN",
    aliases: ["saigon", "ho chi minh city"],
    timezone: "Asia/Ho_Chi_Minh",
    currency: "VND",
    language: "vi-VN",
  }),
  createDestination({
    id: "taipei-tw",
    city: "Taipei",
    country: "Taiwan",
    countryCode: "TW",
    aliases: ["taipei taiwan"],
    timezone: "Asia/Taipei",
    currency: "TWD",
    language: "zh-TW",
  }),
  createDestination({
    id: "kuala-lumpur-my",
    city: "Kuala Lumpur",
    country: "Malásia",
    countryCode: "MY",
    aliases: ["malasia", "malásia"],
    timezone: "Asia/Kuala_Lumpur",
    currency: "MYR",
    language: "ms-MY",
  }),

  // África
  createDestination({
    id: "cidade-do-cabo-za",
    city: "Cidade do Cabo",
    country: "África do Sul",
    countryCode: "ZA",
    aliases: ["cape town", "cape town south africa"],
    timezone: "Africa/Johannesburg",
    currency: "ZAR",
    language: "en-ZA",
  }),
  createDestination({
    id: "johanesburgo-za",
    city: "Johanesburgo",
    country: "África do Sul",
    countryCode: "ZA",
    aliases: ["johannesburg"],
    timezone: "Africa/Johannesburg",
    currency: "ZAR",
    language: "en-ZA",
  }),
  createDestination({
    id: "kruger-za",
    city: "Kruger",
    country: "África do Sul",
    countryCode: "ZA",
    aliases: ["parque kruger", "safari africano"],
    timezone: "Africa/Johannesburg",
    currency: "ZAR",
    language: "en-ZA",
  }),
  createDestination({
    id: "marrakech-ma",
    city: "Marrakech",
    country: "Marrocos",
    countryCode: "MA",
    aliases: ["marrakesh"],
    timezone: "Africa/Casablanca",
    currency: "MAD",
    language: "ar-MA",
  }),
  createDestination({
    id: "casablanca-ma",
    city: "Casablanca",
    country: "Marrocos",
    countryCode: "MA",
    aliases: ["casablanca marrocos"],
    timezone: "Africa/Casablanca",
    currency: "MAD",
    language: "ar-MA",
  }),
  createDestination({
    id: "cairo-eg",
    city: "Cairo",
    country: "Egito",
    countryCode: "EG",
    aliases: ["cairo egypt", "pirâmides", "piramides"],
    timezone: "Africa/Cairo",
    currency: "EGP",
    language: "ar-EG",
  }),
  createDestination({
    id: "zanzibar-tz",
    city: "Zanzibar",
    country: "Tanzânia",
    countryCode: "TZ",
    aliases: ["tanzania", "tanzânia"],
    timezone: "Africa/Dar_es_Salaam",
    currency: "TZS",
    language: "sw-TZ",
  }),
  createDestination({
    id: "seychelles-sc",
    city: "Seychelles",
    country: "Seychelles",
    countryCode: "SC",
    aliases: ["seicheles", "mahe", "mahé"],
    timezone: "Indian/Mahe",
    currency: "SCR",
    language: "en-SC",
  }),
  createDestination({
    id: "mauricio-mu",
    city: "Maurício",
    country: "Maurício",
    countryCode: "MU",
    aliases: ["mauricio", "mauritius"],
    timezone: "Indian/Mauritius",
    currency: "MUR",
    language: "en-MU",
  }),

  // Oceania
  createDestination({
    id: "sydney-au",
    city: "Sydney",
    country: "Austrália",
    countryCode: "AU",
    aliases: ["sidney", "sydney australia"],
    timezone: "Australia/Sydney",
    currency: "AUD",
    language: "en-AU",
  }),
  createDestination({
    id: "melbourne-au",
    city: "Melbourne",
    country: "Austrália",
    countryCode: "AU",
    aliases: ["melbourne australia"],
    timezone: "Australia/Melbourne",
    currency: "AUD",
    language: "en-AU",
  }),
  createDestination({
    id: "brisbane-au",
    city: "Brisbane",
    country: "Austrália",
    countryCode: "AU",
    aliases: ["brisbane australia"],
    timezone: "Australia/Brisbane",
    currency: "AUD",
    language: "en-AU",
  }),
  createDestination({
    id: "gold-coast-au",
    city: "Gold Coast",
    country: "Austrália",
    countryCode: "AU",
    aliases: ["gold coast australia"],
    timezone: "Australia/Brisbane",
    currency: "AUD",
    language: "en-AU",
  }),
  createDestination({
    id: "auckland-nz",
    city: "Auckland",
    country: "Nova Zelândia",
    countryCode: "NZ",
    aliases: ["new zealand auckland", "nova zelandia"],
    timezone: "Pacific/Auckland",
    currency: "NZD",
    language: "en-NZ",
  }),
  createDestination({
    id: "queenstown-nz",
    city: "Queenstown",
    country: "Nova Zelândia",
    countryCode: "NZ",
    aliases: ["queenstown new zealand", "aventura nova zelandia"],
    timezone: "Pacific/Auckland",
    currency: "NZD",
    language: "en-NZ",
  }),
  createDestination({
    id: "fiji-fj",
    city: "Fiji",
    country: "Fiji",
    countryCode: "FJ",
    aliases: ["ilhas fiji"],
    timezone: "Pacific/Fiji",
    currency: "FJD",
    language: "en-FJ",
  }),
  createDestination({
    id: "tahiti-pf",
    city: "Tahiti",
    country: "Polinésia Francesa",
    countryCode: "PF",
    aliases: ["taiti", "polinesia francesa", "polinésia francesa"],
    timezone: "Pacific/Tahiti",
    currency: "XPF",
    language: "fr-PF",
  }),

  // Ilhas e lua de mel
  createDestination({
    id: "maldivas-mv",
    city: "Maldivas",
    country: "Maldivas",
    countryCode: "MV",
    aliases: ["maldives", "male", "malé", "lua de mel"],
    timezone: "Indian/Maldives",
    currency: "MVR",
    language: "dv-MV",
  }),
  createDestination({
    id: "bora-bora-pf",
    city: "Bora Bora",
    country: "Polinésia Francesa",
    countryCode: "PF",
    aliases: ["lua de mel polinesia", "honeymoon bora bora"],
    timezone: "Pacific/Tahiti",
    currency: "XPF",
    language: "fr-PF",
  }),
  createDestination({
    id: "moorea-pf",
    city: "Moorea",
    country: "Polinésia Francesa",
    countryCode: "PF",
    aliases: ["moorea island"],
    timezone: "Pacific/Tahiti",
    currency: "XPF",
    language: "fr-PF",
  }),
  createDestination({
    id: "como-it",
    city: "Lago de Como",
    country: "Itália",
    countryCode: "IT",
    aliases: ["lake como", "como italy"],
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  }),
  createDestination({
    id: "amalfi-it",
    city: "Costa Amalfitana",
    country: "Itália",
    countryCode: "IT",
    aliases: ["amalfi coast", "positano", "sorrento"],
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "it-IT",
  }),
  createDestination({
    id: "reykjavik-is",
    city: "Reykjavik",
    country: "Islândia",
    countryCode: "IS",
    aliases: ["iceland", "islandia", "islândia"],
    timezone: "Atlantic/Reykjavik",
    currency: "ISK",
    language: "is-IS",
  }),
  createDestination({
    id: "lapland-fi",
    city: "Lapônia",
    country: "Finlândia",
    countryCode: "FI",
    aliases: ["laponia", "rovaniemi", "aurora boreal finlandia"],
    timezone: "Europe/Helsinki",
    currency: "EUR",
    language: "fi-FI",
  }),
  createDestination({
    id: "banff-ca",
    city: "Banff",
    country: "Canadá",
    countryCode: "CA",
    aliases: ["rocky mountains canada", "banff canada"],
    timezone: "America/Edmonton",
    currency: "CAD",
    language: "en-CA",
  }),
  createDestination({
    id: "toronto-ca",
    city: "Toronto",
    country: "Canadá",
    countryCode: "CA",
    aliases: ["toronto canada"],
    timezone: "America/Toronto",
    currency: "CAD",
    language: "en-CA",
  }),
  createDestination({
    id: "vancouver-ca",
    city: "Vancouver",
    country: "Canadá",
    countryCode: "CA",
    aliases: ["vancouver canada"],
    timezone: "America/Vancouver",
    currency: "CAD",
    language: "en-CA",
  }),
  createDestination({
    id: "mexico-city-mx",
    city: "Cidade do México",
    country: "México",
    countryCode: "MX",
    aliases: ["mexico city", "cdmx", "cidade do mexico"],
    timezone: "America/Mexico_City",
    currency: "MXN",
    language: "es-MX",
  }),
]

export function normalizeDestinationText(value?: string | null) {
  return (value ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9,\s-]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
}

function getSearchTokens(option: DestinationOption) {
  return [
    option.id,
    option.city,
    option.country,
    option.countryCode,
    option.label,
    ...option.aliases,
  ].map((value) => normalizeDestinationText(value))
}

export function getDestinationOptionById(id?: string | null) {
  if (!id) return null
  return DESTINATION_CATALOG.find((option) => option.id === id) ?? null
}

export function searchDestinationOptions(query: string, limit = 6) {
  const normalizedQuery = normalizeDestinationText(query)
  if (!normalizedQuery) {
    return DESTINATION_CATALOG.slice(0, limit)
  }

  return [...DESTINATION_CATALOG]
    .map((option) => {
      const tokens = getSearchTokens(option)
      const score = tokens.reduce((best, token) => {
        if (token === normalizedQuery) return Math.max(best, 100)
        if (token.startsWith(normalizedQuery)) return Math.max(best, 80)
        if (token.includes(normalizedQuery)) return Math.max(best, 60)
        if (normalizedQuery.includes(token)) return Math.max(best, 40)
        return best
      }, 0)

      return { option, score }
    })
    .filter((entry) => entry.score > 0)
    .sort((left, right) => right.score - left.score || left.option.label.localeCompare(right.option.label))
    .slice(0, limit)
    .map((entry) => entry.option)
}

export function resolveDestinationOption(input?: string | null, selectedId?: string | null) {
  const selected = getDestinationOptionById(selectedId)
  if (selected) return selected

  const normalizedInput = normalizeDestinationText(input)
  if (!normalizedInput) return null

  const exact = DESTINATION_CATALOG.find((option) =>
    getSearchTokens(option).some((token) => token === normalizedInput)
  )
  if (exact) return exact

  return null
}

export function resolveDestinationInput(input: string, selectedId?: string | null): ResolvedDestinationInput {
  const matchedOption = resolveDestinationOption(input, selectedId)
  if (matchedOption) {
    return {
      id: matchedOption.id,
      label: matchedOption.label,
      city: matchedOption.city,
      country: matchedOption.country,
      countryCode: matchedOption.countryCode,
      coverImageUrl: matchedOption.coverImageUrl ?? null,
      timezone: matchedOption.timezone ?? null,
      currency: matchedOption.currency ?? null,
      language: matchedOption.language ?? null,
      matchedCatalog: true,
    }
  }

  const normalizedLabel = input.trim()
  const parts = normalizedLabel.split(",").map((part) => part.trim()).filter(Boolean)

  return {
    id: null,
    label: normalizedLabel,
    city: parts[0] || normalizedLabel || null,
    country: parts.length > 1 ? parts[parts.length - 1] : null,
    countryCode: null,
    coverImageUrl: null,
    timezone: null,
    currency: null,
    language: null,
    matchedCatalog: false,
  }
}
